# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tblog
  seed: 1337

checkpoint:
  save_interval: 1
  keep_last_epochs: 1
  keep_best_checkpoints: -1
  best_checkpoint_metric: macro_f1
  restore_file: checkpoint_last.pt
  maximize_best_checkpoint_metric: true

distributed_training:
  ddp_backend: legacy_ddp
  find_unused_parameters: true
  distributed_world_size: 1
  distributed_port: -1
  nprocs_per_node: 8

task:
  _name: slue_audio_classification
  data: ???
  normalize: false  # must be consistent with pre-training
  labels: sent

dataset:
  num_workers: 0
  max_tokens: 1600000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: ${model.freeze_finetune_updates}
  validate_interval: 1000000
  train_subset: train
  valid_subset: valid
  required_batch_size_multiple: 1

criterion:
  _name: speechlm_sequence_classification

optimization:
  max_update: 30000
  lr: [0.00002]
  sentence_avg: true
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08
  weight_decay: 0.0

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: speechlm_seq_cls
  pool_method: avg
  classifier_dropout: 0.2
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.5
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 2000
  freeze_layers: 0

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
          - model.w2v_path
          - dataset.train_subset
          - dataset.valid_subset
          - criterion.wer_kenlm_model
          - criterion.wer_lexicon
  run:
    dir: ???
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
